language: csharp
solution: ./src/WOL.sln
sudo: false
install:
  - nuget restore ./src/WOL.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release /p:PostBuildEventUseInBuild=false /p:PreBuildEvent="" /p:PostBuildEvent="" /p:TargetFrameworkProfile="" ./src/WOL.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./src/WakeOnLan.Testing/bin/Release/WakeOnLan.Testing.dll
